### ISSUE TITLE
ToDo has been implemented

### ISSUE THREAD

**Issue by fivdi** [joba-1/Blink-ULP#1]
The [ToDo mentioned in the readme](https://github.com/joba-1/Blink-ULP#todo) has been implemented so I guess that section of the readme could be removed now.

**Comment by joba-1** [comment]
Cool, someone is actually looking at this. Thanks for the hint.

**Comment by fivdi** [comment]
> Cool, someone is actually looking at this.

Yes :smile:

I like the way everything done in the .S file and only needs to be loaded and run from the main program. Nice job.
